package com.govmedcare.utils;

public interface QueryUtil {
     String saveUser="Insert into users(name,email,password,role,phone,address) VALUES(?,?,?,?,?,?)";
     String checkByEmail="SELECT * FROM users where email=?";
     String saveMedicine="Insert into medicines(name,description,price,quantity,category_id,image_url) VALUES (?,?,?,?,?,?)";
     String checkByName="SELECT * FROM medicines where name=?";
     String getCategories="Select * from categories";
     String getPendingMedicines ="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.is_verified = false";;
     String getApprovedMedicines ="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.is_verified = true";
     String validateMedicines="Update medicines SET is_verified=true where medicine_id=?";
     String deleteMedicine="UPDATE medicines SET is_verified = false WHERE medicine_id = ?";
     String getActiveUsers =    "SELECT * FROM users WHERE status='active' AND role='PATIENT'";
     String blockUser="UPDATE users set status='blocked' WHERE user_id=?";
     String getAllMedicineAndCategory="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id;";
     String getMedicinesByCategory = "SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ?";
     String countPending  = "SELECT COUNT(*) FROM medicines WHERE is_verified = false";
     String countApproved = "SELECT COUNT(*) FROM medicines WHERE is_verified = true";
     String updateStock="UPDATE medicines set quantity= quantity + ? where medicine_id=?";
     String createCart = "INSERT INTO cart(patient_id) VALUES(?)";
     String getCartByUser = "SELECT * FROM cart WHERE patient_id=?";
     String checkCartMedicine = "SELECT * FROM cart_items WHERE cart_id=? AND medicine_id=?";
     String addCartItem = "INSERT INTO cart_items(cart_id,medicine_id,quantity) VALUES(?,?,?)";
     String updateCartQuantity = "UPDATE cart_items SET quantity=quantity+? WHERE cart_id=? AND medicine_id=?";
     String getCartItems = "SELECT m.medicine_id, m.name, m.price, ci.quantity  FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id JOIN medicines m ON ci.medicine_id = m.medicine_id WHERE c.patient_id=?";
     String createOrder = "INSERT INTO orders(patient_id,total_amount,status) VALUES(?,?,?)";
     String saveOrderItem = "INSERT INTO order_items(order_id,medicine_id,quantity,price) VALUES(?,?,?,?)";
     String savePayment = "INSERT INTO payments(order_id,amount,payment_method,payment_status) VALUES(?,?,?,?)";
     String reduceMedicineStock = "UPDATE medicines SET quantity = quantity - ? WHERE medicine_id = ?";
     String clearCart = "DELETE ci FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id WHERE c.patient_id=?";
     String getApprovedMedicinesByCategoryAsc = "SELECT m.*, c.name AS category_name " + "FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ? AND m.is_verified = true ORDER BY m.price ASC";
     String getApprovedMedicinesByCategoryDesc = "SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ? AND m.is_verified = true ORDER BY m.price DESC";
     String getPurchaseHistory="Select * from orders where patient_id=? ORDER BY created_at desc";
     String getSoldHistory = "SELECT oi.order_id, oi.medicine_id, m.name AS medicine_name, oi.quantity, oi.price, o.created_at, u.name AS patient_name FROM order_items oi JOIN orders o ON oi.order_id = o.order_id JOIN users u ON o.patient_id = u.user_id JOIN medicines m ON oi.medicine_id = m.medicine_id ORDER BY o.created_at DESC";
     String getMedicineById = "SELECT * FROM medicines WHERE medicine_id = ?";
     String updateUserInfo="UPDATE users set name=?,phone=?,address=?,updated_at=? WHERE user_id=?";
     String calculateTotalRevenue="SELECT SUM(total_amount) AS total_revenue from orders WHERE status='Completed'";
     String getTotalActiveUsers="SELECT COUNT(user_id) AS active_users FROM users where status='active'";
     String getTotalBlockedUsers="SELECT COUNT(user_id) AS blocked_users FROM users where status='blocked'";
     String decreaseCartQuantity="UPDATE cart_items ci JOIN cart c ON ci.cart_id = c.cart_id SET ci.quantity = ci.quantity - 1 WHERE c.patient_id = ? AND ci.medicine_id = ? AND ci.quantity > 1";
     String increaseCartQuantity="UPDATE cart_items ci JOIN cart c ON ci.cart_id = c.cart_id SET ci.quantity = ci.quantity + 1 WHERE c.patient_id = ? AND ci.medicine_id = ?";
     String removeSingleItemFromCart="DELETE ci FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id WHERE c.patient_id = ? AND ci.medicine_id = ?;";
}
