package com.govmedcare.utils;

public class QueryUtil {
   public static final String saveUser="Insert into users(name,email,password,role,phone,address) VALUES(?,?,?,?,?,?)";
   public static final String checkByEmail="SELECT * FROM users where email=?";
   public static final String saveMedicine="Insert into medicines(name,description,price,quantity,category_id,image_url) VALUES (?,?,?,?,?,?)";
   public static final String checkByName="SELECT * FROM medicines where name=?";
   public static final String getCategories="Select * from categories";
   public static final String getPendingMedicines ="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.is_verified = false";;
   public static final String getApprovedMedicines ="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.is_verified = true";
   public static final String validateMedicines="Update medicines SET is_verified=true where medicine_id=?";
   public static final String deleteMedicine="DELETE from medicines where medicine_id=?";
   public static final String getUsers="SELECT * FROM users where status='active'";
   public static final String blockUser="UPDATE users set status='blocked' WHERE user_id=?";
   public static final String getAllMedicineAndCategory="SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id;";
   public static final String getMedicinesByCategory = "SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ?";
   public static final String countPending  = "SELECT COUNT(*) FROM medicines WHERE is_verified = false";
   public static final String countApproved = "SELECT COUNT(*) FROM medicines WHERE is_verified = true";
   public static final String updateStock="UPDATE medicines set quantity= quantity + ? where medicine_id=?";
   public static final String createCart = "INSERT INTO cart(patient_id) VALUES(?)";
   public static final String getCartByUser = "SELECT * FROM cart WHERE patient_id=?";
   public static final String checkCartMedicine = "SELECT * FROM cart_items WHERE cart_id=? AND medicine_id=?";
   public static final String addCartItem = "INSERT INTO cart_items(cart_id,medicine_id,quantity) VALUES(?,?,?)";
   public static final String updateCartQuantity = "UPDATE cart_items SET quantity=quantity+? WHERE cart_id=? AND medicine_id=?";
   public static final String getCartItems = "SELECT m.medicine_id, m.name, m.price, ci.quantity  FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id JOIN medicines m ON ci.medicine_id = m.medicine_id WHERE c.patient_id=?";
   public static final String createOrder = "INSERT INTO orders(patient_id,total_amount,status) VALUES(?,?,?)";
   public static final String saveOrderItem = "INSERT INTO order_items(order_id,medicine_id,quantity,price) VALUES(?,?,?,?)";
   public static final String savePayment = "INSERT INTO payments(order_id,amount,payment_method,payment_status) VALUES(?,?,?,?)";
   public static final String reduceMedicineStock = "UPDATE medicines SET quantity = quantity - ? WHERE medicine_id = ?";
   public static final String clearCart = "DELETE ci FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id WHERE c.patient_id=?";
   public static final String getApprovedMedicinesByCategoryAsc = "SELECT m.*, c.name AS category_name " + "FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ? AND m.is_verified = true ORDER BY m.price ASC";
   public static final String getApprovedMedicinesByCategoryDesc = "SELECT m.*, c.name AS category_name FROM medicines m JOIN categories c ON m.category_id = c.category_id WHERE m.category_id = ? AND m.is_verified = true ORDER BY m.price DESC";
   public static final String getPurchaseHistory="Select * from orders where patient_id=? ORDER BY created_at desc";
   public static final String getSoldHistory="SELECT oi.order_id,oi.medicine_id,m.name AS medicine_name,oi.quantity,oi.price,o.created_at FROM order_items oi JOIN orders o ON oi.order_id = o.order_id JOIN medicines m ON oi.medicine_id = m.medicine_id where supplier_id=? ORDER BY o.created_at DESC";
   public static final String getMedicineById = "SELECT * FROM medicines WHERE medicine_id = ?";
   public static final String updateUserInfo="UPDATE users set name=?,phone=?,address=?,updated_at=? WHERE user_id=?";
   public static final String calculateTotalRevenue="SELECT SUM(total_amount) AS total_revenue from orders WHERE status='Completed'";
   public static final String getTotalActiveUsers="SELECT COUNT(user_id) AS active_users FROM users where status='active'";
   public static final String getTotalBlockedUsers="SELECT COUNT(user_id) AS blocked_users FROM users where status='blocked'";
   public static final String decreaseCartQuantity="UPDATE cart_items ci JOIN cart c ON ci.cart_id = c.cart_id SET ci.quantity = ci.quantity - 1 WHERE c.patient_id = ? AND ci.medicine_id = ? AND ci.quantity > 1";
   public static final String increaseCartQuantity="UPDATE cart_items ci JOIN cart c ON ci.cart_id = c.cart_id SET ci.quantity = ci.quantity + 1 WHERE c.patient_id = ? AND ci.medicine_id = ?";
   public static final String removeSingleItemFromCart="DELETE ci FROM cart_items ci JOIN cart c ON ci.cart_id = c.cart_id WHERE c.patient_id = ? AND ci.medicine_id = ?;";
}
